name: snapshot

on:
  push:
    branches:
     - master
  
  pull_request:
    branches:
      - master
  

jobs:

  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - name: chackout code
      uses: actions/checkout@v2
    
    - name: install node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16'
    
    - name: install npm packages
      run: npm ci

    - name: build project
      run: npm run build

    - name: run tests
      run: npm run test

    - name: upload production
      uses: actions/upload-artifact@v2
      with:
        name: production-file
        uses: ./build

  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.rf == 'refs/heads/master'

    steps:

    - name: download articals
      uses: actions/download-artifacrt@v2
      with:
        name: production-file
        uses: ./build

    - name: deploy to gh-pages
      uses: peaceiris/action-gh-pages@v3
      with: 
        github_token: ${{ secrate.GITHUB_TOKEN }}
        publish_dir: ./build